### PR TITLE
Fix #49

### LINKED ISSUE #49: Using nameof_member on structures with non-constexpr destructor fails to compile on MSVC
Hi, I finally got around to updating nameof in my project to test the fix of #46 by @schaumb.
Unfortunately, it doesn't work when `TestStruct` has a member with a non-constexpr user-provided constructor. Is it possible to fix it?
I looked into the source, but I don't understand the union trick used in the `member_name_v` implementation for MSVC, so I can't tell if it can be fixed.

As previously, the following code doesn't compile on MSVC (2022) using the latest master of `nameof`, but works fine with clang and gcc
```
struct Foo{
    ~Foo(){};
};

struct TestStruct{
    std::string teststringfield = std::string{nameof::nameof_member<&TestStruct::teststringfield>()};
    Foo foo;
};
```

### PR DESCRIPTION
**Pull request by kamchatka-volcano**
Used `union_type` as a static member to fix the issue #49 
Added unit tests for fixes of issues #49 and #46

### CODE REVIEW

File: test/test.cpp [hunk 1]
```diff
@@ -118,6 +118,15 @@ struct TestRtti{
   struct Derived : Base {};
 };
 
+struct StructMemberInitializationUsingNameof{
```
Comment (Neargye) [inline test/test.cpp:121]: #if defined(NAMEOF_MEMBER_SUPPORTED) && NAMEOF_MEMBER_SUPPORTED

File: include/nameof.hpp [hunk 2]
```diff
@@ -979,14 +979,17 @@ union union_type {
 };
 
 template <typename T>
-inline constexpr auto static_v = T{};
+struct union_type_holder
```
Comment (Neargye) [inline include/nameof.hpp:982]: `struct union_type_holder {`
